import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { Card } from "../components/Card";
import { Header } from "../components/Header";

const Home: NextPage = () => {
  const data = [
    {
      title: "タイトル1",
      id: "vEwFIwW3mg0",
      comments: [
        {
          title: "ここ",
          start: 10,
          end: 15,
          comment: "こうした方がいいと思う",
        },
        {
          title: "ここ",
          start: 100,
          end: 102,
          comment: "こうした方がいいと思う",
        },
        {
          title: "ここ",
          start: 205,
          end: 210,
          comment: "こうした方がいいと思う",
        },
        {
          title: "ここ",
          start: 210,
          end: 215,
          comment: "こうした方がいいと思う",
        },
        {
          title: "ここ",
          start: 220,
          end: 222,
          comment: "こうした方がいいと思う",
        },
        {
          title: "ここ",
          start: 240,
          end: 242,
          comment: "こうした方がいいと思う",
        },
        {
          title: "ここ",
          start: 1000,
          end: 1004,
          comment: "こうした方がいいと思う",
        },
        {
          title: "ここ",
          start: 2000,
          end: 2003,
          comment: "こうした方がいいと思う",
        },
      ],
    },
    {
      title: "タイトル2",
      id: "oXd0e-TQkII",
      comments: [
        {
          title: "ここ",
          start: 10,
          end: 15,
          comment: "こうした方がいいと思う",
        },
        {
          title: "ここ",
          start: 100,
          end: 102,
          comment: "こうした方がいいと思う",
        },
      ],
    },
    {
      title: "タイトル3",
      id: "O3mS6ft7ylE",
      comments: [
        {
          title: "ここ",
          start: 10,
          end: 15,
          comment: "こうした方がいいと思う",
        },
        {
          title: "ここ",
          start: 100,
          end: 102,
          comment: "こうした方がいいと思う",
        },
      ],
    },
    {
      title: "タイトル4",
      id: "PB-Ac9IcGcI",
      comments: [
        {
          title: "ここ",
          start: 10,
          end: 15,
          comment: "こうした方がいいと思う",
        },
        {
          title: "ここ",
          start: 100,
          end: 102,
          comment: "こうした方がいいと思う",
        },
      ],
    },
  ];

  return (
    <div>
      <Head>
        <title>Youtube Feecback</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <ul className="grid lg:grid-cols-3 gap-4 w-11/12 md:w-9/12">
          {data.map((data) => {
            return (
              <Card
                title={data.title}
                id={data.id}
                comments={data.comments}
                key={data.id}
              />
            );
          })}
        </ul>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
